name: Deploy on Prod Branch

on:
  push:
    branches:
      - deploy-backup-disabled

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t academy-backend:${{ github.sha }} .
          docker tag academy-backend:${{ github.sha }} academy-backend:latest

      - name: Save Docker image
        run: docker save academy-backend:latest -o academy-backend.tar

      - name: Copy to server and deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "academy-backend.tar,deploy.sh"
          target: "/tmp/deploy"

      - name: Execute deploy script on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /tmp/deploy
            chmod +x deploy.sh
            ./deploy.sh
